version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb
      - KC_DB_URL_DATABASE=${MYSQL_DATABASE}
      - KC_DB_URL_PORT=3306
      - KC_DB_USERNAME=${MYSQL_USER}
      - KC_DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    depends_on:
      - mariadb
    networks:
      - custom-network

  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - custom-network
  
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 7000:80
    networks:
      - custom-network

volumes:
  mariadb_data:
networks:
  custom-network:
