FROM quay.io/keycloak/keycloak:latest as builder
EXPOSE 8080

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running mariadb instance
# Configure a database vendor
ENV KC_DB=mariadb
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_DB_URL_HOST=mariadb
ENV KC_DB_URL_DATABASE=keycloak
ENV KC_DB_URL_PORT=3306
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=admin@123
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
